#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ステージングされたts,tsxファイルをスペース区切りで取得
files=`git diff --cached --name-only | grep -E "*.ts|tsx$" | tr "\r\n" " " | tr "\n" " "`

if [ -n "${files}" ]; then
  echo "[pre-commit] Find *.tx|tsx, Exec lint."

  pnpm lint:fix $files
  ret=$?
  if [ $ret != 0 ]; then
    echo "[pre-commit] Lint error."
    exit $ret
  fi
fi

exit 0
